config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get '/update-data' => 'ajax#update_data'

  root 'dashboard#index'
  resources :tasks
  resources :jobs
  resources :task_executions
  resources :users
  resources :user_sessions
  resources :roles
  resources :task_states
  resources :group_assignments
  resources :packages
  resources :package_groups
  resources :systems
  resources :system_groups
  resources :concrete_package_versions
  resources :concrete_package_states
  resources :package_versions
  resources :distributions
  resources :repositories
  resources :system_package_relations

  post '/jobs/create_multiple' => 'jobs#create_multiple'
  post '/jobs/create_combo' => 'jobs#create_combo'

  put '/jobs/:id/execute' => 'jobs#execute'
  get '/assign-systems'  => 'system_assignment#index',  :as => :assign_systems
  get '/assign-packages' => 'package_assignment#index', :as => :assign_packages
  post '/group_assignments/create_remote' => 'group_assignments#create_remote'

  scope '/api' do
    scope module: 'api' do
      namespace :v1 do
        match "/register" => "api#register", via: :post
        match "/system/:id/notify" => "api#updateSystem", via: :post
        match "/task/:id/notify" => "api#updateTask", via: :post
        match "/system/:id/updateInstalled" => "api#updateInstalled", via: :post
      end

      namespace :v2 do
        match "/register"                           => "api#register", via: :post
        match "/system/:urn/notify-hash"            => "api#updateSystemHash", via: :post
        match "/system/:urn/notify"                 => "api#updateSystem", via: :post
        match "/system/:urn/refresh-installed-hash" => "api#refreshInstalledHash", via: :post
        match "/system/:urn/refresh-installed"      => "api#refreshInstalled", via: :post
        match "/task/:id/notify"                    => "api#updateTask", via: :post
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  helper_method :get_running_tasks,
                :get_failed_tasks,
                :get_not_recently_seen_systems,
                :get_systems_without_group,
                :get_packages_without_group,
                :get_tasks_for_recent_activities,
                :get_overdue_tasks,
                :get_systems_with_queued_updates,
                :get_systems_without_updates_or_queued,
                :get_systems_with_available_updates_only

  #load_and_authorize_resource

  # GET /dashboard
  def index
    cpv_state_avail = ConcretePackageState.where(name: "Available")[0]

    @systems = System.all
    @packages = Package.all
    @tasks = Task.all
    @updates = ConcretePackageVersion.where(concrete_package_state: cpv_state_avail)

    @updatable_systems = @systems.reject{ |s| s.get_installable_CPVs.count < 1 }
    @updatable_system_groups = SystemGroup.all.reject{ |g| !g.has_installable_CPVs }
  end

  def get_running_tasks
    statePending = TaskState.where(name: "Pending")[0]
    @tasks.where(task_state: statePending)
  end

  def get_failed_tasks
    stateFailed = TaskState.where(name: "Failed")[0]
    @tasks.where(task_state: stateFailed)
  end

  def get_not_recently_seen_systems
    @systems.is_missing
  end

  def get_systems_without_group
    unassigned = SystemGroup.where(name: "Unassigned-System")[0]
    @systems.where( system_group: [ nil, unassigned ] )
  end

  def get_packages_without_group
    #@packages.reject{|pkg| !pkg.group_assignments.empty?}
    @packages.joins('left join group_assignments on packages.id = group_assignments.package_id where package_group_id is null')
  end

  def get_tasks_for_recent_activities
    @tasks.order(:created_at ).reverse_order.limit(Settings.Systems.NoOfShownRecentTasks)
  end

  def get_overdue_tasks
    pending = TaskState.where(name: "Pending")[0]
    queued = TaskState.where(name: "Queued")[0]

    @tasks.where( "created_at < ?", (Time.now - (Settings.Tasks.OverdueWarningThresholdMinutes).minutes ) ).where( task_state: [queued, pending ] )
  end

  def get_systems_with_queued_updates
    @systems.reject{ |s| s.get_queued_CPVs.count == 0 }
  end

  def get_systems_without_updates_or_queued
    @systems.reject{ |s| s.get_queued_CPVs.count > 0 || s.get_installable_CPVs.count > 0 }
  end

  def get_systems_with_available_updates_only
    @updatable_systems.reject{ |s| s.get_queued_CPVs.count > 0 }
  end
end

app/views/dashboard/index.html.erb
<%= render :partial => "header", :object => {
  "title" => "UPD89",
  "actions" =>[]
} %>

<div class="col_12">
  <p class="col_12">Hello, <%= link_to current_user.name, user_path(current_user.id) %>!</p>

  <div class="col_8 dashboard_box sysBG">
    <h4>Systems</h4>
    <div class="col_6">
      <div id="systemChart"
           data-total="<%= @systems.count %>"
           data-ok="<%= get_systems_without_updates_or_queued.count %>"
           data-progress="<%= get_systems_with_queued_updates.count %>"
           data-warning="<%= get_systems_with_available_updates_only.count %>"></div>
    </div>
    <div class="col_6">
      <ul>
        <li><%= @systems.count %> Systems present</li>
        <% if get_not_recently_seen_systems.count > 0 %>
        <li><%= get_not_recently_seen_systems.count %> <%= "System".pluralize(get_not_recently_seen_systems.count) %> not seen in past <%= Settings.Systems.NotSeenWarningThresholdMinutes / 60 %> hours <%= link_to("(Check)", systems_path( filterrific: { sorted_by: "last_seen_asc" } ) ) %></li>
        <% end %>
        <% if get_systems_without_group.count > 0 %>
        <li><%= get_systems_without_group.count %> <%= "System".pluralize(get_systems_without_group.count) %> not in a group</li>
        <% end %>
      </ul>

      <% if get_systems_without_group.count > 0 %>
        <%= link_to("Assign to a group", :assign_systems, class: "button") %>
      <% end %>
    </div>
    <div class="floatFix"></div>
  </div>

  <div class="col_4 dashboard_box pkgBG">
    <h4>Packages</h4>

    <ul>
      <li><%= @packages.count %> known <%= "Package".pluralize(@packages.count) %></li>
      <% if get_packages_without_group.count > 0 %>
      <li><%= get_packages_without_group.count %> <%= "Package".pluralize(get_packages_without_group.count) %> not in a group</li>
      <% end %>
    </ul>

    <% if get_packages_without_group.count > 0 %>
      <%= link_to("Assign to groups", :assign_packages, class: "button") %>
    <% end %>
    <div class="floatFix"></div>
  </div>

  <div class="floatFix"></div>

  <div class="col_6 dashboard_box">
    <h4>Tasks</h4>

    <% if get_running_tasks.count + get_failed_tasks.count + get_overdue_tasks.count == 0 %>
      <p>Nothing to report!</p>
    <% end %>

    <ul class="noDots">
    <% if get_running_tasks.count > 0 %>
      <li><%= get_running_tasks.count %> pending <%= link_to( "Task".pluralize(get_running_tasks.count)  , tasks_path( filterrific: { with_state_id: TaskState.where(name: "Pending")[0].id } ) ) %></li>
    <% end %>

    <% if get_failed_tasks.count > 0 %>
      <li class="errorText"><i class="fa fa-exclamation-triangle"></i> <%= get_failed_tasks.count %> failed <%= "Task".pluralize(get_failed_tasks.count) %>! (<%= link_to("Check", tasks_path( filterrific: { with_state_id: TaskState.where(name: "Failed")[0].id } ) ) %>)</li>
    <% end %>

    <% if get_overdue_tasks.count > 0 %>
      <li class="warnText"><i class="fa fa-clock-o"></i> <%= get_overdue_tasks.count %> <%= "Task".pluralize(get_overdue_tasks.count) %> overdue!
          <% get_overdue_tasks.take( Settings.Dashboard.NrOfOverdueTasksShown ).each do |task| %>
          <div><%= task.decorated_created_at %> (<%= task.task_state.name %>) <%= link_to "Cancel", task_path( task ), method: :delete %> <%= link_to "Check", task_path( task )  %></div>
          <% end %>
          <% if get_overdue_tasks.count > Settings.Dashboard.NrOfOverdueTasksShown %>...<% end %>
      </li>
    <% end %>

    </ul>

    <div class="floatFix"></div>
  </div>

  <div class="col_6 dashboard_box sysBG">
    <h4><%= link_to( "Available Updates", concrete_package_versions_path( filterrific: { with_state_id: ConcretePackageState.where(name: "Available")[0].id } ) ) %></h4>
    <div class="col_6">
      <h6>By System:</h6>
      <% @updatable_systems.take( Settings.Dashboard.NrOfEntitiesWithUpdatesShown ).each do |sys| %>
        <div><%= link_to(sys.name, sys) + ": " + sys.get_installable_CPVs.count.to_s %></div>
      <% end %>
      <% if @updatable_systems.count > Settings.Dashboard.NrOfEntitiesWithUpdatesShown %>...<% end %>
    </div>

    <div class="col_6">
      <h6>By Group:</h6>
      <% @updatable_system_groups.take( Settings.Dashboard.NrOfEntitiesWithUpdatesShown ).each do |sys_grp| %>
        <div><%= link_to(sys_grp.name, sys_grp) + ": " + sys_grp.get_nr_of_installable_CPVs.to_s %></div>
      <% end %>
      <% if @updatable_system_groups.count > Settings.Dashboard.NrOfEntitiesWithUpdatesShown %>...<% end %>
    </div>
    <div class="floatFix"></div>
  </div>

  <div class="col_12 dashboard_box">
    <h4>Recent Activity</h4>
    <% get_tasks_for_recent_activities.each do |t| %>
      <div><%= link_to( t.to_full_sentence + t.state_description, t) %></div>
    <% end %>
    <div class="floatFix"></div>
  </div>
</div>

<div class="floatFix"></div>