config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get '/update-data' => 'ajax#update_data'

  root 'dashboard#index'
  resources :tasks
  resources :jobs
  resources :task_executions
  resources :users
  resources :user_sessions
  resources :roles
  resources :task_states
  resources :group_assignments
  resources :packages
  resources :package_groups
  resources :systems
  resources :system_groups
  resources :concrete_package_versions
  resources :concrete_package_states
  resources :package_versions
  resources :distributions
  resources :repositories
  resources :system_package_relations

  post '/jobs/create_multiple' => 'jobs#create_multiple'
  post '/jobs/create_combo' => 'jobs#create_combo'

  put '/jobs/:id/execute' => 'jobs#execute'
  get '/assign-systems'  => 'system_assignment#index',  :as => :assign_systems
  get '/assign-packages' => 'package_assignment#index', :as => :assign_packages
  post '/group_assignments/create_remote' => 'group_assignments#create_remote'

  scope '/api' do
    scope module: 'api' do
      namespace :v1 do
        match "/register" => "api#register", via: :post
        match "/system/:id/notify" => "api#updateSystem", via: :post
        match "/task/:id/notify" => "api#updateTask", via: :post
        match "/system/:id/updateInstalled" => "api#updateInstalled", via: :post
      end

      namespace :v2 do
        match "/register"                           => "api#register", via: :post
        match "/system/:urn/notify-hash"            => "api#updateSystemHash", via: :post
        match "/system/:urn/notify"                 => "api#updateSystem", via: :post
        match "/system/:urn/refresh-installed-hash" => "api#refreshInstalledHash", via: :post
        match "/system/:urn/refresh-installed"      => "api#refreshInstalled", via: :post
        match "/task/:id/notify"                    => "api#updateTask", via: :post
      end
    end
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  def full_name
      origin + " " + archive + " " + component
  end

  # used in api
  def self.get_maybe_create(rep)
    repo_obj = nil
    begin
      self.transaction(isolation: :serializable) do
        repo_obj = self.find_or_create_by(
          archive: rep['archive'],
          origin: rep['origin'],
          component: rep['component']
        )
      end
    rescue ActiveRecord::StatementInvalid
      logger.debug("ActiveRecord: StatementInvalid Exception")
      retry
    end
    return repo_obj
  end
  
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # POST /repositories
  def create
    @repository = Repository.new(repository_params)

    if @repository.save
      redirect_to @repository, success: 'Repository was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /repositories/1
  def update
    if @repository.update(repository_params)
      redirect_to @repository, success: 'Repository was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /repositories/1
  def destroy
    @repository.destroy
    redirect_to repositories_url, success: 'Repository was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repository_params
      params.require(:repository).permit(:origin, :archive, :component)
    end
end

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="properties col_6">
      <li>
      <p>
          <span class="property">origin</span>
        <span class="value"><%= f.text_field :origin %></span>
            </p>
    </li>
      <li>
      <p>
          <span class="property">archive</span>
        <span class="value"><%= f.text_field :archive %></span>
            </p>
    </li>
      <li>
      <p>
          <span class="property">component</span>
        <span class="value"><%= f.text_field :component %></span>
            </p>
    </li>
    </ul>

  <div class="actions">
    <%= f.button "Save", :class => "button" %>
  </div>

<% end %>

app/views/repositories/edit.html.erb
<%= render :partial => "header", :object => {
  "title" => "Edit Repository",
  "actions" =>[{
    "icon" => "arrow-left",
    "text" => "",
    "path" => repositories_path
  }, {
    "icon" => "eye",
    "text" => "",
    "path" => @repository
  }, {
    "icon" => "remove",
    "text" => "",
    "path" => @repository,
    "ctrlAction" => :destroy,
    "method" => :delete,
    "confirm" => "Are you sure you want to delete this Repository?"
  }]
} %>

<%= render 'form' %>

<div class="floatFix"></div>

app/views/repositories/index.html.erb
<%= render :partial => "header", :object => {
  "title" => "Repositories",
  "actions" =>[{
    "icon" => "plus",
    "text" => "New Repository",
    "path" => new_repository_path,
    "ctrlAction" => :create
  }]
} %>

<table class="striped tight sortable clickableRows">
  <thead>
    <tr>
      <th>Origin</th>
      <th>Archive</th>
      <th>Component</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= repository.origin %></td>
        <td><%= repository.archive %></td>
        <td><%= repository.component %></td>
        <td>
          <ul class="button-bar">
            <% if can? :read, repository    %><li><%= link_to '<i class="fa fa-arrow-right"></i>'.html_safe, repository %></li><% end %>
            <% if can? :update, repository  %><li><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_repository_path(repository) %></li><% end %>
            <% if can? :destroy, repository %><li><%= link_to '<i class="fa fa-remove"></i>'.html_safe, repository, method: :delete, data: { confirm: 'Are you sure?' } %></li><% end %>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/repositories/new.html.erb
<%= render :partial => "header", :object => {
  "title" => "New Repository",
  "actions" =>[{
    "icon" => "arrow-left",
    "text" => "",
    "path" => repositories_path
  }]
} %>

<%= render 'form' %>

<div class="floatFix"></div>

app/views/repositories/show.html.erb
<%= render :partial => "header", :object => {
  "title" => "Repository",
  "actions" =>[{
    "icon" => "arrow-left",
    "text" => "",
    "path" => repositories_path
  }, {
    "icon" => "pencil",
    "text" => "",
    "ctrlAction" => :update,
    "path" => edit_repository_path(@repository)
  }, {
    "icon" => "remove",
    "text" => "",
    "path" => @repository,
    "method" => :delete,
    "ctrlAction" => :destroy,
    "confirm" => "Are you sure you want to delete this Repository?"
  }]
} %>

<ul class="properties col_6">
  <li>
    <p>
      <span class="property">Origin</span>
      <span class="value"><%= @repository.origin %></span>
    </p>
  </li>
  <li>
    <p>
      <span class="property">Archive</span>
      <span class="value"><%= @repository.archive %></span>
    </p>
  </li>
  <li>
    <p>
      <span class="property">Component</span>
      <span class="value"><%= @repository.component %></span>
    </p>
  </li>
</ul>

<div class="floatFix"></div>