config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get '/update-data' => 'ajax#update_data'

  root 'dashboard#index'
  resources :tasks
  resources :jobs
  resources :task_executions
  resources :users
  resources :user_sessions
  resources :roles
  resources :task_states
  resources :group_assignments
  resources :packages
  resources :package_groups
  resources :systems
  resources :system_groups
  resources :concrete_package_versions
  resources :concrete_package_states
  resources :package_versions
  resources :distributions
  resources :repositories
  resources :system_package_relations

  post '/jobs/create_multiple' => 'jobs#create_multiple'
  post '/jobs/create_combo' => 'jobs#create_combo'

  put '/jobs/:id/execute' => 'jobs#execute'
  get '/assign-systems'  => 'system_assignment#index',  :as => :assign_systems
  get '/assign-packages' => 'package_assignment#index', :as => :assign_packages
  post '/group_assignments/create_remote' => 'group_assignments#create_remote'

  scope '/api' do
    scope module: 'api' do
      namespace :v1 do
        match "/register" => "api#register", via: :post
        match "/system/:id/notify" => "api#updateSystem", via: :post
        match "/task/:id/notify" => "api#updateTask", via: :post
        match "/system/:id/updateInstalled" => "api#updateInstalled", via: :post
      end

      namespace :v2 do
        match "/register"                           => "api#register", via: :post
        match "/system/:urn/notify-hash"            => "api#updateSystemHash", via: :post
        match "/system/:urn/notify"                 => "api#updateSystem", via: :post
        match "/system/:urn/refresh-installed-hash" => "api#refreshInstalledHash", via: :post
        match "/system/:urn/refresh-installed"      => "api#refreshInstalled", via: :post
        match "/task/:id/notify"                    => "api#updateTask", via: :post
      end
    end
  end
end

app/models/concrete_package_state.rb
class ConcretePackageState < ActiveRecord::Base
  validates_presence_of :name
  
  def self.options_for_select
    order('LOWER(name)').map { |e| [e.name, e.id] }
  end
end

app/controllers/concrete_package_states_controller.rb
class ConcretePackageStatesController < ApplicationController
  before_action :set_concrete_package_state, only: [:show, :edit, :update, :destroy]

  # GET /concrete_package_states
  # GET /concrete_package_states.json
  def index
    @concrete_package_states = ConcretePackageState.all
  end

  # GET /concrete_package_states/1
  # GET /concrete_package_states/1.json
  def show
  end

  # GET /concrete_package_states/new
  def new
    @concrete_package_state = ConcretePackageState.new
  end

  # GET /concrete_package_states/1/edit
  def edit
  end

  # POST /concrete_package_states
  # POST /concrete_package_states.json
  def create
    @concrete_package_state = ConcretePackageState.new(concrete_package_state_params)

    respond_to do |format|
      if @concrete_package_state.save
        format.html { redirect_to @concrete_package_state, success: 'Concrete package state was successfully created.' }
        format.json { render :show, status: :created, location: @concrete_package_state }
      else
        format.html { render :new }
        format.json { render json: @concrete_package_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concrete_package_states/1
  # PATCH/PUT /concrete_package_states/1.json
  def update
    respond_to do |format|
      if @concrete_package_state.update(concrete_package_state_params)
        format.html { redirect_to @concrete_package_state, success: 'Concrete package state was successfully updated.' }
        format.json { render :show, status: :ok, location: @concrete_package_state }
      else
        format.html { render :edit }
        format.json { render json: @concrete_package_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concrete_package_states/1
  # DELETE /concrete_package_states/1.json
  def destroy
    @concrete_package_state.destroy
    respond_to do |format|
      format.html { redirect_to concrete_package_states_url, success: 'Concrete package state was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concrete_package_state
      @concrete_package_state = ConcretePackageState.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concrete_package_state_params
      params.require(:concrete_package_state).permit(:name)
    end
end

app/views/concrete_package_states/_form.html.erb
<%= form_for(@concrete_package_state) do |f| %>
  <% if @concrete_package_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concrete_package_state.errors.count, "error") %> prohibited this concrete_package_state from being saved:</h2>

      <ul>
      <% @concrete_package_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="properties col_6">
    <li>
      <p>
        <span class="property">name</span>
        <span class="value"><%= f.text_field :name %></span>
      </p>
    </li>
  </ul>

  <div class="actions">
    <%= f.button "Save", :class => "button" %>
  </div>

<% end %>

app/views/concrete_package_states/edit.html.erb
<%= render partial: "header", object: {
  "title" => "Edit Concrete Package State",
  "actions" =>[{
    "icon" => "arrow-left",
    "text" => "",
    "path" => concrete_package_states_path
  }, {
    "icon" => "eye",
    "text" => "",
    "path" => @concrete_package_state
  }, {
    "icon" => "remove",
    "text" => "",
    "path" => @concrete_package_state,
    "method" => :delete,
    "confirm" => "Are you sure you want to delete this Concrete Package State?"
  }]
} %>

<%= render 'form' %>

<div class="floatFix"></div>

app/views/concrete_package_states/index.html.erb
<%= render :partial => "header", :object => {
  "title" => "Concrete Package States",
  "actions" =>[{
    "icon" => "plus",
    "text" => "New Concrete package state",
    "path" => new_concrete_package_state_path
  }]
} %>

<table class="striped tight sortable clickableRows">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @concrete_package_states.each do |concrete_package_state| %>
      <tr>
        <td><%= concrete_package_state.name %></td>
        <td>
          <ul class="button-bar">
            <li><%= link_to '<i class="fa fa-arrow-right"></i>'.html_safe, concrete_package_state %></li>
            <li><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_concrete_package_state_path(concrete_package_state) %></li>
            <li><%= link_to '<i class="fa fa-remove"></i>'.html_safe, concrete_package_state, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/concrete_package_states/new.html.erb
<%= render :partial => "header", :object => {
  "title" => "New Concrete Package State",
  "actions" =>[{
    "icon" => "arrow-left",
    "text" => "",
    "path" => concrete_package_states_path
  }]
} %>

<%= render 'form' %>

<div class="floatFix"></div>

app/views/concrete_package_states/show.html.erb
<%= render :partial => "header", :object => {
  "title" => "Concrete Package State",
  "actions" =>[{
    "icon" => "arrow-left",
    "text" => "",
    "path" => concrete_package_states_path
  }, {
    "icon" => "pencil",
    "text" => "",
    "path" => edit_concrete_package_state_path(@concrete_package_state)
  }, {
    "icon" => "remove",
    "text" => "",
    "path" => @concrete_package_state,
    "method" => :delete,
    "confirm" => "Are you sure you want to delete this Concrete Package State?"
  }]
} %>

<ul class="properties col_6">
  <li>
    <p>
      <span class="property">Name</span>
      <span class="value"><%= @concrete_package_state.name %></span>
    </p>
  </li>
</ul>

<div class="floatFix"></div>