config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get '/update-data' => 'ajax#update_data'

  root 'dashboard#index'
  resources :tasks
  resources :jobs
  resources :task_executions
  resources :users
  resources :user_sessions
  resources :roles
  resources :task_states
  resources :group_assignments
  resources :packages
  resources :package_groups
  resources :systems
  resources :system_groups
  resources :concrete_package_versions
  resources :concrete_package_states
  resources :package_versions
  resources :distributions
  resources :repositories
  resources :system_package_relations

  post '/jobs/create_multiple' => 'jobs#create_multiple'
  post '/jobs/create_combo' => 'jobs#create_combo'

  put '/jobs/:id/execute' => 'jobs#execute'
  get '/assign-systems'  => 'system_assignment#index',  :as => :assign_systems
  get '/assign-packages' => 'package_assignment#index', :as => :assign_packages
  post '/group_assignments/create_remote' => 'group_assignments#create_remote'

  scope '/api' do
    scope module: 'api' do
      namespace :v1 do
        match "/register" => "api#register", via: :post
        match "/system/:id/notify" => "api#updateSystem", via: :post
        match "/task/:id/notify" => "api#updateTask", via: :post
        match "/system/:id/updateInstalled" => "api#updateInstalled", via: :post
      end

      namespace :v2 do
        match "/register"                           => "api#register", via: :post
        match "/system/:urn/notify-hash"            => "api#updateSystemHash", via: :post
        match "/system/:urn/notify"                 => "api#updateSystem", via: :post
        match "/system/:urn/refresh-installed-hash" => "api#refreshInstalledHash", via: :post
        match "/system/:urn/refresh-installed"      => "api#refreshInstalled", via: :post
        match "/task/:id/notify"                    => "api#updateTask", via: :post
      end
    end
  end
end

app/models/distribution.rb
class Distribution < ActiveRecord::Base

  # used in api
  def self.get_maybe_create(distro)
    distro_obj = nil
    begin
      self.transaction(isolation: :serializable) do
        distro_obj = self.find_or_create_by(name: distro)
      end
    rescue ActiveRecord::StatementInvalid
      logger.debug("ActiveRecord: StatementInvalid Exception")
      retry
    end
    return distro_obj
  end
  
end

app/controllers/distributions_controller.rb
class DistributionsController < ApplicationController
  before_action :set_distribution, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # POST /distributions
  def create
    @distribution = Distribution.new(distribution_params)

    if @distribution.save
      redirect_to @distribution, success: 'Distribution was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /distributions/1
  def update
    if @distribution.update(distribution_params)
      redirect_to @distribution, success: 'Distribution was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /distributions/1
  def destroy
    @distribution.destroy
    redirect_to distributions_url, success: 'Distribution was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distribution
      @distribution = Distribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distribution_params
      params.require(:distribution).permit(:name)
    end
end

app/views/distributions/_form.html.erb
<%= form_for(@distribution) do |f| %>
  <% if @distribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@distribution.errors.count, "error") %> prohibited this distribution from being saved:</h2>

      <ul>
      <% @distribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="properties col_6">
      <li>
      <p>
          <span class="property">name</span>
        <span class="value"><%= f.text_field :name %></span>
            </p>
    </li>
    </ul>

  <div class="actions">
    <%= f.button "Save", :class => "button" %>
  </div>

<% end %>

app/views/distributions/edit.html.erb
<%= render :partial => "header", :object => {
  "title" => "Edit Distribution",
  "actions" =>[{
    "icon" => "arrow-left",
    "text" => "",
    "path" => distributions_path
  }, {
    "icon" => "eye",
    "text" => "",
    "path" => @distribution
  }, {
    "icon" => "remove",
    "text" => "",
    "path" => @distribution,
    "method" => :delete,
    "confirm" => "Are you sure you want to delete this Distribution?"
  }]
} %>

<%= render 'form' %>

<div class="floatFix"></div>

app/views/distributions/index.html.erb
<%= render :partial => "header", :object => {
  "title" => "Distributions",
  "actions" =>[{
    "icon" => "plus",
    "text" => "New Distribution",
    "path" => new_distribution_path,
    "ctrlAction" => :create
  }]
} %>

<table class="striped tight sortable clickableRows">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @distributions.each do |distribution| %>
      <tr>
        <td><%= distribution.name %></td>
        <td>
          <ul class="button-bar">
            <% if can? :read, distribution    %><li><%= link_to '<i class="fa fa-arrow-right"></i>'.html_safe, distribution %></li><% end %>
            <% if can? :update, distribution  %><li><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_distribution_path(distribution) %></li><% end %>
            <% if can? :destroy, distribution %><li><%= link_to '<i class="fa fa-remove"></i>'.html_safe, distribution, method: :delete, data: { confirm: 'Are you sure?' } %></li><% end %>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/distributions/new.html.erb
<%= render :partial => "header", :object => {
  "title" => "New Distribution",
  "actions" =>[{
    "icon" => "arrow-left",
    "text" => "",
    "path" => distributions_path
  }]
} %>

<%= render 'form' %>

<div class="floatFix"></div>

app/views/distributions/show.html.erb
<%= render :partial => "header", :object => {
  "title" => "Distribution",
  "actions" =>[{
    "icon" => "arrow-left",
    "text" => "",
    "path" => distributions_path
  }, {
    "icon" => "pencil",
    "text" => "",
    "path" => edit_distribution_path(@distribution),
    "ctrlAction" => :update
  }, {
    "icon" => "remove",
    "text" => "",
    "path" => @distribution,
    "method" => :delete,
    "ctrlAction" => :destroy,
    "confirm" => "Are you sure you want to delete this Distribution?"
  }]
} %>

<ul class="properties col_6">
  <li>
    <p>
      <span class="property">Name</span>
      <span class="value"><%= @distribution.name %></span>
    </p>
  </li>
</ul>

<div class="floatFix"></div>